internal enum ChatReasonCode
{
	STR_CHAT_REASON_NONE,
	STR_CHAT_REASON_UNEXPECTED_ERROR,
	STR_CHAT_REASON_FLOOD,
	STR_CHAT_REASON_MUTED,
	STR_CHAT_REASON_USER_NOT_ONLINE,
	STR_CHAT_REASON_USER_DOES_NOT_EXIST,
	STR_CHAT_REASON_NO_CONNECTION,
	STR_CHAT_REASON_MODERATORS_ONLY,
	STR_CHAT_REASON_ADMINS_ONY,
	STR_CHAT_REASON_SANCTION_ALREADY_EXISTS,
	STR_CHAT_REASON_ALREADY_WARNED,
	STR_CHAT_REASON_NO_SANCTION_EXISTS
}
