internal enum GameServerErrorCodes
{
	STR_ERR_HAX_SPEED = 0,
	STR_ERR_HAX_EXCEPTION = 1,
	STR_ERR_HAX_TELEPORT = 2,
	STR_ERR_HAX_EAC_VIOLATION = 6,
	STR_ERR_HAX_AFK = 7,
	STR_ERR_HAX_FIRERANGE = 8,
	STR_ERR_HAX_FIREDAMAGE = 9,
	STR_ERR_HAX_FIRERATE = 10,
	STR_ERR_HAX_FIREPOSITION = 11,
	STR_ERR_INCORRECT_GAME_GUID = 12,
	STR_ERR_CUSTOM_STRING = 13,
	STR_ERR_TIMED_OUT = 14,
	STR_ERR_GAME_ENDED = 0xF
}
