internal enum ReasonCode
{
	STR_REASON_CODE_TIME_OUT,
	STR_REASON_CODE_DATA_CORRUPTED,
	STR_REASON_CODE_MESSAGE_NOT_CORRECTLY_SETUP,
	STR_REASON_CODE_SERVER_DID_NOT_REPLY_CORRECTLY,
	STR_REASON_CODE_IMPOSSIBLE_TO_SEND_MESSAGE,
	STR_REASON_CODE_SERVER_WAS_UNABLE_TO_REPLY,
	STR_REASON_CODE_CLIENT_HAS_BEEN_DISCONNECTED,
	STR_REASON_CODE_SUCCESS_FUNCTION_FAILED,
	STR_REASON_CODE_SERVER_ERROR,
	STR_REASON_CODE_IMPOSSIBLE_TO_CONNECT_TO_THE_SERVER
}
