namespace Mothership.GUI
{
	internal enum BrawlDetailsFields
	{
		LOCKED,
		NO_LONGER_USED,
		BONUS_SEASON_XP_MULTIPLIER,
		BONUS_SEASON_XP_MULTIPLIER_STRING,
		TITLE,
		DESCRIPTION,
		RULES,
		DETAILS_IMAGE,
		DETAILS_IMAGE_OFF,
		DETAILS_TOP_IMAGE,
		GAME_MODE,
		FIRST_VICTORY_BONUS
	}
}
