namespace SocialServiceLayer.Photon
{
	public enum SocialOperationCode : byte
	{
		InviteFriend = 0,
		AcceptFriend = 1,
		DeclineFriend = 2,
		RemoveFriend = 3,
		RequestFriendList = 4,
		CancelFriendInvite = 5,
		MyAvatarHasChanged = 6,
		InviteToPlatoon = 10,
		AcceptPlatoonInvite = 11,
		DeclinePlatoonInvite = 12,
		LeavePlatoon = 13,
		KickFromPlatoon = 14,
		SetPlatoonMemberStatus = 17,
		GetPlatoonData = 18,
		GetPlatoonInvites = 19,
		CheckPartyRobotTiers = 20,
		GetSettings = 24,
		SetSetting = 25,
		StartFriendChat = 30,
		CreateClan = 0x1F,
		SearchClans = 0x20,
		GetClanInfo = 33,
		JoinClan = 34,
		InviteToClan = 35,
		AcceptClanInvite = 36,
		DeclineClanInvite = 37,
		ChangeClanMemberRank = 38,
		GetClanInvites = 39,
		LeaveClan = 40,
		RemoveFromClan = 41,
		ChangeClanData = 42,
		GetMyClanInfo = 43,
		DeclineAllClanInvites = 44,
		CancelClanInvite = 45,
		RenameClan = 46,
		PlatoonRobotTierChange = 47,
		FetchSeasonRewards = 50,
		ReclaimSeasonRewardsRequest = 51,
		ValidateSeasonRewardsRequest = 52,
		GetNewPreviousBattleRewardsRequest = 53,
		HasNewPreviousBattleRewardsRequest = 54,
		CollectPreviousBattleRewardsRequest = 55,
		PollClanExperience = 57,
		GetPlayerCanBeInvitedToCustomGame = 58,
		GetPlayerCanBeInvitedToRegularParty = 59
	}
}
