using CustomGames;
using Mothership;
using Services.Local;
using Services.Requests.Interfaces;
using Services.TechTree;
using Services.Web;
using Services.Web.Photon;
using Services.Web.Photon.Tencent;
using Simulation;
using Svelto.ServiceLayer;

namespace WebServices
{
	internal abstract class WebStorageRequestFactory : ServiceRequestFactory
	{
		protected WebStorageRequestFactory()
		{
			AddRelation<ILoadCubeListRequest, GetCubeListRequest>();
			AddRelation<ILoadTiersBandingRequest, LoadTiersBandingRequest>();
			AddRelation<ILoadPlayerRobotRankingRequest, LoadPlayerRobotRankingRequest>();
			AddRelation<ILoadPlayerLevelDataRequest, GetPlayerLevelDataRequest>();
			AddRelation<IGetABTestGroupRequest, GetABTestGroupRequest>();
			AddRelation<IGetRoboPassPreviewItemsRequest, GetRoboPassPreviewItemsRequest>();
			AddRelation<ILoadIncomeScalesPremiumFactorRequest, GetIncomeScalesPremiumDataRequest>();
			AddRelation<ILoadSpecialItemListRequest, GetSpecialItemListRequest>();
			AddRelation<ILoadPremiumDataRequest, GetPremiumDataRequest>();
			AddRelation<ILoadUserCubeInventoryRequest, GetCubesInventoryRequest>();
			AddRelation<ILoadChatSettingsRequest, GetChatSettingsRequest>();
			AddRelation<ILoadDefaultColorPaletteRequest, LoadDefaultColorPaletteRequest>();
			AddRelation<ILoadMachineColorMapRequest, LoadMachineColorMapRequest, LoadMachineColorMapDependancy>();
			AddRelation<ISaveMachineColorRequest, SaveMachineColorRequest, SaveMachineColorDependency>();
			AddRelation<IGetGameClientSettingsRequest, GetGameClientSettingsRequest>();
			AddRelation<IGetGameModeSettingsRequest, GetGameModeSettingsRequest>();
			AddRelation<IGetBuildingXPSettingsRequest, GetBuildingXPSettingsRequest>();
			AddRelation<IGetAutoRegenHealthSettings, GetAutoRegenHealthSettings>();
			AddRelation<IGetPowerBarSettingsRequest, GetPowerBarSettingsRequest>();
			AddRelation<IGetDamageBoostRequest, GetDamageBoostRequest>();
			AddRelation<IGetTauntsRequest, GetTauntsRequest>();
			AddRelation<ILoadMachineRequest, LoadMachineRequest, uint?>();
			AddRelation<ISetSelectedRobotRequest, SetSelectedRobotRequest, SetSelectedRobotDependency>();
			AddRelation<IDeleteGarageRequest, DeleteGarageRequest, uint>();
			AddRelation<IDismantleGarageRobotRequest, DismantleGarageRobotRequest, uint>();
			AddRelation<ISaveMachineRequest, SaveRobotRequest, SaveMachineDependency>();
			AddRelation<ISetRobotNameRequest, SetRobotNameRequest, SetRobotNameDependency>();
			AddRelation<IClearMachineRequest, ClearMachineRequest, uint>();
			AddRelation<IValidateCurrentMachineRequest, ValidateCurrentMachineRequest>();
			AddRelation<ISetRobotInGameRequest, SinglePlayer_SetRobotInGameRequest, float>();
			AddRelation<IUpdateThumbnailVersionRequest, UpdateThumbnailVersionRequest, UpdateThumbnailVersionRequestDependancy>();
			AddRelation<ILoadAllCustomisationInfoRequest, LoadAllCustomisationsInfoRequest>();
			AddRelation<IGetRobotBayCustomisationsRequest, GetRobotBayCustomisationsRequest, string>();
			AddRelation<ISetRobotCustomisationsRequest, SetRobotCustomisationsRequest, SetRobotCustomisationDependency>();
			AddRelation<ILoadWeaponStatsRequest, LoadWeaponStatsRequest>();
			AddRelation<ILoadMovementStatsRequest, LoadMovementStatsRequest>();
			AddRelation<ILoadVotingAfterBattleThresholdsRequest, LoadVotingAfterBattleThresholdsRequest>();
			AddRelation<ILoadItemShopBundleListRequest, LoadItemShopBundleListRequest>();
			AddRelation<IBuyItemShopBundleRequest, BuyItemShopBundleRequest, ItemShopBundle>();
			AddRelation<IGetAccountRightsRequest, GetAccountRightsRequest>();
			AddRelation<ILoadCRFItemListRequest, LoadCRFItemListRequest, CRFShopItemListDependency>();
			AddRelation<ILoadCRFShopItemDataRequest, LoadCRFShopItemDataRequest, int>();
			AddRelation<IUpdateShotRobotOffsetRequest, UpdateShopRobotOffsetRequest, UpdateShopRobotOffsetDependency>();
			AddRelation<ILoadShopEarningsRequest, LoadShopEarningsRequest>();
			AddRelation<IClaimShopEarningsRequest, ClaimShopEarningsRequest>();
			AddRelation<ISubmitCRFRatingRequest, SubmitCRFRatingRequest, SubmitCRFRatingDependency>();
			AddRelation<ILoadRobotShopConfigRequest, LoadRobotShopConfigRequest>();
			AddRelation<ILoadRobotShopSubmissionInfos, LoadRobotShopSubmissionInfos>();
			AddRelation<IRemovePlayerShopSubmission, RemovePlayerShopSubmission, int>();
			AddRelation<IReportCommunityShopItemRequest, ReportCommunityShopItemRequest, ReportCommunityShopItemDependency>();
			AddRelation<ILoadRobotShopItem, LoadRobotShopItem>();
			AddRelation<ISetCRFRobotAsFeaturedRequest, SetCRFRobotAsFeaturedRequest, int>();
			AddRelation<IHideCRFFeaturedRobotRequest, HideCRFFeaturedRobotRequest, int>();
			AddRelation<IRestoreCRFFeaturedRobotRequest, RestoreCRFFeaturedRobotRequest, int>();
			AddRelation<ILoadRobotHashFromDiskCache, LoadRobotHashFromDiskCache, LoadRobotHashFromDiskCacheDependency>();
			AddRelation<IClearRobotHashFromDiskCache, ClearRobotHashFromDiskCache>();
			AddRelation<ISaveRobotHashToDiskCache, SaveRobotHashToDiskCache, SaveRobotHashToDiskCacheDependency>();
			AddRelation<ILoadTextureFromURLRequest, LoadTextureFromURLRequest, string>();
			AddRelation<ILoadThumbnailTextureFromDiskCache, LoadThumbnailTextureFromDiskCache, LoadThumbnailFromDiskCacheDependency>();
			AddRelation<ISaveThumbnailTextureToDiskCache, SaveThumbnailTextureToDiskCache, SaveTextureToDiskCacheDependency>();
			AddRelation<ILoadWalletRequest, LoadWalletRequest>();
			AddRelation<ILoadTechPointsRequest, LoadTechPointsRequest>();
			AddRelation<ILoadHintProgressRequest, LoadHintProgressRequest>();
			AddRelation<ISaveHintProgressRequest, SaveHintProgressRequest, byte[]>();
			AddRelation<ISaveLastMatchResultRequest, SaveLastMatchResultRequest, bool>();
			AddRelation<ILoadLastMatchResultRequest, LoadLastMatchResultRequest>();
			AddRelation<ISaveUserOptionsRequest, SaveUserOptionsRequest, UserOptionsData>();
			AddRelation<ILoadUserOptionsRequest, LoadUserOptionsRequest>();
			AddRelation<ILoadGarageSlotLimitRequest, LoadGarageSlotLimitRequest>();
			AddRelation<IBuyGarageSlotRequest, AddNewGarageSlotRequest>();
			AddRelation<ILoadTotalXPRequest, LoadTotalXPRequest>();
			AddRelation<ISaveChatSettingsRequest, SaveChatSettingsRequest, ChatSettingsData>();
			AddRelation<IResetDemoAccount, ResetDemoAccount>();
			AddRelation<IGetGameStartAudioRequest, GetGameStartAudioRequest>();
			AddRelation<ILoadSignupDate, LoadSignupDate>();
			AddRelation<ILoadIfPlayerIsModeratorRequest, LoadIfPlayerIsModeratorRequest>();
			AddRelation<ILoadLeagueBattleParametersRequest, LoadLeagueBattleParametersRequest>();
			AddRelation<IMarkTierProgressNotificationSeenRequest, MarkTierProgressNotificationSeenRequest>();
			AddRelation<ILoadPurchasesRequest, LoadPurchasesRequest>();
			AddRelation<ILoadPlatformConfigurationRequest, LoadPlatformConfigurationRequest>();
			AddRelation<IGetAvatarInfoRequest, GetAvatarInfoRequest>();
			AddRelation<ISetAvatarInfoRequest, SetAvatarInfoRequest, AvatarInfo>();
			AddRelation<IUploadCustomAvatarRequest, UploadCustomAvatarRequest, byte[]>();
			AddRelation<IGetGarageBayUniqueIdRequest, GetGarageBayUniqueIdRequest>();
			AddRelation<ISetGarageSlotOrderRequest, SetGarageSlotOrderRequest, SetGarageSlotOrderDependency>();
			AddRelation<ISetGarageSlotControlsRequest, SetGarageSlotControlsRequest, GarageSlotControlsDependency>();
			AddRelation<IGetCurrentRobotControlsRequest, GetCurrentRobotControlsRequest>();
			AddRelation<IGetScoreMultipliersTeamDeathMatchAIRequest, GetScoreMultipliersTeamDeathMatchAIRequest>();
			AddRelation<IGetDefaultWeaponOrderSubcategoriesRequest, GetDefaultWeaponOrderSubcategoriesRequest>();
			AddRelation<ILoadTutorialStatusRequest, LoadTutorialStatusRequest>();
			AddRelation<IUpdateTutorialStatusRequest, UpdateTutorialStatusRequest>();
			AddRelation<ILoadTutorialStageRequest, LoadTutorialStageRequest>();
			AddRelation<IUpdateTutorialStageRequest, UpdateTutorialStageRequest>();
			AddRelation<ISwitchToTutorialRobotRequest, SwitchToTutorialRobotRequest>();
			AddRelation<ISwitchToPreviousRobotIfNecessaryRequest, SwitchToPreviousRobotIfNecessaryRequest>();
			AddRelation<IResetTutorialRobotRequest, ResetTutorialRobotRequest, ResetTutorialRobotDependancy>();
			AddRelation<ILoadTutorialEnemyMachineRequest, LoadTutorialEnemyMachineRequest>();
			AddRelation<IGetNewInventoryCubesRequest, GetNewInventoryCubesRequest>();
			AddRelation<ISetNewInventoryCubesRequest, SetNewInventoryCubesRequest>();
			AddRelation<IGetBrawlParametersRequest, GetBrawlParametersRequest>();
			AddRelation<IValidateBrawlRobotRequest, ValidateBrawlRobotRequest>();
			AddRelation<ILoadImageTextureRequest, LoadImageTextureRequest, LoadImageDependency>();
			AddRelation<ILoadBrawlLanguageOverrides, LoadBrawlLanguageOverridesRequest>();
			AddRelation<ILoadFirstBrawlVictoryPendingRequest, LoadFirstBrawlVictoryPendingRequest, int>();
			AddRelation<ILoadBattleArenaSettingsRequest, LoadBattleArenaSettingsRequest>();
			AddRelation<IGetPlayerStartedPurchaseRequest, GetPlayerStartedPurchaseRequest>();
			AddRelation<ILoadPlayerDataRequest, LoadPlayerDataRequest>();
			AddRelation<ILeaveCustomGameSessionRequest, LeaveCustomGameSessionRequest>();
			AddRelation<ICreateCustomGameSessionRequest, CreateCustomGameSessionRequest>();
			AddRelation<IRetrieveCustomGameSessionRequest, RetrieveCustomGameSessionRequest>();
			AddRelation<ILoadCustomGamesAllowedMapsRequest, LoadCustomGamesAllowedMapsRequest>();
			AddRelation<IDispatchCustomGameInvitationRequest, DispatchCustomGameInvitationRequest, DispatchCustomGameInviteDependancy>();
			AddRelation<IRespondToCustomGameInvitationRequest, RespondToCustomGameInvitationRequest, RespondToCustomGameInvitationDependancy>();
			AddRelation<IAdjustCustomGameConfigRequest, AdjustCustomGameConfigRequest, AdjustCustomGameConfigRequestDependancy>();
			AddRelation<IKickFromCustomGameRequest, KickFromCustomGameRequest, KickFromCustomGameRequestDependancy>();
			AddRelation<IChangeTeamAssignmentRequest, ChangeTeamAssignmentRequest, ChangeCustomGameTeamAssignmentDependancy>();
			AddRelation<ICustomGamePlayerStateChangedRequest, CustomGamePlayerStateChangedRequest, CustomGamePlayerSessionStatus>();
			AddRelation<ICheckIfHasBeenInvitedToCustomGameSessionRequest, CheckIfHasBeenInvitedToCustomGameSessionRequest>();
			AddRelation<ICheckIfCanJoinCustomGameQueueResponse, CheckIfCanJoinCustomGameQueueRequest>();
			AddRelation<ICustomGameGetTeamSetupRequest, CustomGameGetTeamSetupRequest, GameModeType>();
			AddRelation<ICustomGameRobotTierChangedRequest, CustomGameRobotTierChangedRequest, int>();
			AddRelation<ICopyAndConstructRobotFromCRFRequest, CopyAndConstructRobotFromCRFRequest, CopyAndConstructRobotDependency>();
			AddRelation<IConstructReadOnlyRobotRequest, ConstructReadOnlyRobotRequest, int>();
			AddRelation<ICopyReadOnlyRobotFromGarageRequest, CopyReadOnlyRobotFromGarageRequest, int>();
			AddRelation<ILoadRobotMasterySettingsRequest, LoadRobotMasterySettingsRequest>();
			AddRelation<ILoadCpuSettingsRequest, LoadCpuSettingsRequest>();
			AddRelation<ILoadCosmeticsRenderLimitsRequest, LoadCosmeticsRenderLimitsRequest>();
			AddRelation<ILoadPrebuiltRobotDataRequest, LoadPrebuiltRobotDataRequest>();
			AddRelation<ILoadPrebuiltRobotColorCombinationsRequest, LoadPrebuiltRobotColorCombinationsRequest>();
			AddRelation<ICreatePrebuiltRobotRequest, CreatePrebuiltRobotRequest, CreatePrebuiltRobotDependency>();
			AddRelation<IPingReconnectableGameRequest, PingReconnectableGameRequest>();
			AddRelation<ILoadPlayerDailyQuestsRequest, LoadPlayerDailyQuestsRequest>();
			AddRelation<IReplaceDailyQuestRequest, ReplaceDailyQuestRequest, string>();
			AddRelation<IMarkNotifiedCompletedQuestRequest, MarkNotifiedCompletedQuestRequest>();
			AddRelation<IMarkQuestsAsSeenRequest, MarkQuestsAsSeenRequest>();
			AddRelation<IUpdatePlayerDailyQuestProgressRequest, UpdatePlayerDailyQuestProgressRequest, LocalPlayerDailyQuestProgress>();
			AddRelation<IGetTechTreeDataRequest, GetTechTreeDataRequest>();
			AddRelation<IUnlockTechTreeNodeRequest, UnlockTechTreeNodeRequest>();
			AddRelation<IGetTechPointsAwardRequest, GetTechTreePointsAwardRequest>();
			AddRelation<IPingReconnectableGameRequest, PingReconnectableGameRequest>();
			AddRelation<ICheckRobotSanctionRequest, CheckRobotSanctionRequest, string>();
			AddRelation<ICheckAllRobotsSanctionsRequest, CheckAllRobotsSanctionsRequest>();
			AddRelation<IAcknowledgeRobotSanctionRequest, AcknowledgeRobotSanctionRequest, RobotSanctionData>();
			AddRelation<IMarkTechPointsAwardAsSeenRequest, MarkTechPointsAwardAsSeenRequest>();
			AddRelation<ISavePlayerBuildingXPRequest, SavePlayerBuildingXPRequest>();
			AddRelation<IGetAvailableGameModesRequest, GetAvailableGameModesRequest>();
			AddRelation<IGetGameModePreferencesRequest, GetGameModePreferencesRequest>();
			AddRelation<ISaveGameModePreferencesRequest, SaveGameModePreferencesRequest>();
			AddRelation<IGetTierProgressRequest, GetTierProgressRequest>();
			AddRelation<IGetTierProgressNotificationRequest, GetTierProgressNotificationRequest>();
			AddRelation<ICheckCubeRewardsRequest, CheckCubeRewardsRequest>();
			AddRelation<ILoadRoboPassSeasonConfigRequest, LoadRoboPassSeasonConfigRequest>();
			AddRelation<ILoadPlayerRoboPassSeasonRequest, LoadPlayerRoboPassSeasonRequest>();
			AddRelation<IMarkPlayerRoboPassSeasonProgressAsSeenRequest, MarkPlayerRoboPassSeasonProgressAsSeenRequest>();
			AddRelation<ICreateOrderRequest_Tencent, CreateOrderRequest_Tencent, CreateOrderDependency>();
			AddRelation<IQueryOrderRequest_Tencent, QueryOrderRequest_Tencent, QueryOrderDependency>();
			AddRelation<IGetLongPlayMultiplierRequest, GetLongPlayMultiplierRequest_Tencent>();
			AddRelation<IUploadRobotRequest, UploadRobotRequest_Tencent, UploadRobotDependency>();
		}
	}
}
